alias g='git'
alias galias='git config --get-regexp alias'
alias hidden='ls -ld .?*'
alias ll='ls -l'
alias ls='ls -F --color=auto'
alias bitcode-latest='gsutil stat gs://bitrise-bitcode/bitcode-linux-amd64-latest.tar.gz'
alias bitcode-stable='gsutil stat gs://bitrise-bitcode/bitcode-linux-amd64-stable.tar.gz'